// Code generated by MockGen. DO NOT EDIT.
// Source: persistents/repositories/ponds/index.go

// Package mock_pondsRepositories is a generated GoMock package.
package mock_pondsRepositories

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dao "github.com/naufalfmm/aquafarm-management-service/model/dao"
	dto "github.com/naufalfmm/aquafarm-management-service/model/dto"
)

// MockRepositories is a mock of Repositories interface.
type MockRepositories struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoriesMockRecorder
}

// MockRepositoriesMockRecorder is the mock recorder for MockRepositories.
type MockRepositoriesMockRecorder struct {
	mock *MockRepositories
}

// NewMockRepositories creates a new mock instance.
func NewMockRepositories(ctrl *gomock.Controller) *MockRepositories {
	mock := &MockRepositories{ctrl: ctrl}
	mock.recorder = &MockRepositoriesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositories) EXPECT() *MockRepositoriesMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepositories) Create(ctx context.Context, pond dao.Pond) (dao.Pond, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pond)
	ret0, _ := ret[0].(dao.Pond)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoriesMockRecorder) Create(ctx, pond interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepositories)(nil).Create), ctx, pond)
}

// DeleteByFarmID mocks base method.
func (m *MockRepositories) DeleteByFarmID(ctx context.Context, farmID uint64, deletedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByFarmID", ctx, farmID, deletedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByFarmID indicates an expected call of DeleteByFarmID.
func (mr *MockRepositoriesMockRecorder) DeleteByFarmID(ctx, farmID, deletedBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByFarmID", reflect.TypeOf((*MockRepositories)(nil).DeleteByFarmID), ctx, farmID, deletedBy)
}

// DeleteByID mocks base method.
func (m *MockRepositories) DeleteByID(ctx context.Context, id uint64, deletedBy string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id, deletedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockRepositoriesMockRecorder) DeleteByID(ctx, id, deletedBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockRepositories)(nil).DeleteByID), ctx, id, deletedBy)
}

// GetAll mocks base method.
func (m *MockRepositories) GetAll(ctx context.Context, req dto.PondListRequest) (dao.Ponds, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, req)
	ret0, _ := ret[0].(dao.Ponds)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockRepositoriesMockRecorder) GetAll(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockRepositories)(nil).GetAll), ctx, req)
}

// GetAllPaginated mocks base method.
func (m *MockRepositories) GetAllPaginated(ctx context.Context, req dto.PondPagingRequest) (dao.PondsPagingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPaginated", ctx, req)
	ret0, _ := ret[0].(dao.PondsPagingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPaginated indicates an expected call of GetAllPaginated.
func (mr *MockRepositoriesMockRecorder) GetAllPaginated(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPaginated", reflect.TypeOf((*MockRepositories)(nil).GetAllPaginated), ctx, req)
}

// GetByCode mocks base method.
func (m *MockRepositories) GetByCode(ctx context.Context, code string) (dao.Pond, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(dao.Pond)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockRepositoriesMockRecorder) GetByCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockRepositories)(nil).GetByCode), ctx, code)
}

// GetByID mocks base method.
func (m *MockRepositories) GetByID(ctx context.Context, id uint64) (dao.Pond, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(dao.Pond)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoriesMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepositories)(nil).GetByID), ctx, id)
}

// UpdateByID mocks base method.
func (m *MockRepositories) UpdateByID(ctx context.Context, id uint64, updateMap map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, id, updateMap)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockRepositoriesMockRecorder) UpdateByID(ctx, id, updateMap interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockRepositories)(nil).UpdateByID), ctx, id, updateMap)
}
