// Code generated by MockGen. DO NOT EDIT.
// Source: usecases/endpointLogs/index.go

// Package mock_endpointLogsUsecases is a generated GoMock package.
package mock_endpointLogsUsecases

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dao "github.com/naufalfmm/aquafarm-management-service/model/dao"
	dto "github.com/naufalfmm/aquafarm-management-service/model/dto"
)

// MockUsecases is a mock of Usecases interface.
type MockUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockUsecasesMockRecorder
}

// MockUsecasesMockRecorder is the mock recorder for MockUsecases.
type MockUsecasesMockRecorder struct {
	mock *MockUsecases
}

// NewMockUsecases creates a new mock instance.
func NewMockUsecases(ctrl *gomock.Controller) *MockUsecases {
	mock := &MockUsecases{ctrl: ctrl}
	mock.recorder = &MockUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecases) EXPECT() *MockUsecasesMockRecorder {
	return m.recorder
}

// GetAllReports mocks base method.
func (m *MockUsecases) GetAllReports(ctx context.Context) (dao.EndpointLogReports, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllReports", ctx)
	ret0, _ := ret[0].(dao.EndpointLogReports)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllReports indicates an expected call of GetAllReports.
func (mr *MockUsecasesMockRecorder) GetAllReports(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllReports", reflect.TypeOf((*MockUsecases)(nil).GetAllReports), ctx)
}

// RecordRequestLog mocks base method.
func (m *MockUsecases) RecordRequestLog(ctx context.Context, req dto.RecordRequestLogRequest) (dao.EndpointLog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordRequestLog", ctx, req)
	ret0, _ := ret[0].(dao.EndpointLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecordRequestLog indicates an expected call of RecordRequestLog.
func (mr *MockUsecasesMockRecorder) RecordRequestLog(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRequestLog", reflect.TypeOf((*MockUsecases)(nil).RecordRequestLog), ctx, req)
}
