// Code generated by MockGen. DO NOT EDIT.
// Source: usecases/endpoints/index.go

// Package mock_endpointsUsecases is a generated GoMock package.
package mock_endpointsUsecases

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	dto "github.com/naufalfmm/aquafarm-management-service/model/dto"
)

// MockUsecases is a mock of Usecases interface.
type MockUsecases struct {
	ctrl     *gomock.Controller
	recorder *MockUsecasesMockRecorder
}

// MockUsecasesMockRecorder is the mock recorder for MockUsecases.
type MockUsecasesMockRecorder struct {
	mock *MockUsecases
}

// NewMockUsecases creates a new mock instance.
func NewMockUsecases(ctrl *gomock.Controller) *MockUsecases {
	mock := &MockUsecases{ctrl: ctrl}
	mock.recorder = &MockUsecasesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecases) EXPECT() *MockUsecasesMockRecorder {
	return m.recorder
}

// BulkUpsertEndpoints mocks base method.
func (m *MockUsecases) BulkUpsertEndpoints(ctx context.Context, req dto.BulkUpsertEndpointsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpsertEndpoints", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpsertEndpoints indicates an expected call of BulkUpsertEndpoints.
func (mr *MockUsecasesMockRecorder) BulkUpsertEndpoints(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpsertEndpoints", reflect.TypeOf((*MockUsecases)(nil).BulkUpsertEndpoints), ctx, req)
}
